// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-web-learn/wire/repository"
	"go-web-learn/wire/repository/dao"
)

// Injectors from init.go:

func InitTestRepository() *repository.TestRepository {
	db := InitTestDB()
	testDAO := dao.NewTestDAO(db)
	testRepository := repository.NewTestRepository(testDAO)
	return testRepository
}
